<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>773e2e1a-947f-492e-900e-9f14c42270ad</elementGuidId>
    <imagePath></imagePath>
    <name>list_welcomeMessage</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/ul[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@role,'menu')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ul</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ant-dropdown-menu ant-dropdown-menu-root ant-dropdown-menu-vertical ant-dropdown-menu-light css-s08xz4</value>
        <webElementGuid>20f72bef-7424-48c3-8bb8-a378eade024f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>menu</value>
        <webElementGuid>20f72bef-7424-48c3-8bb8-a378eade024f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Welcome to NextTech
        Sign in for the best experience
        Sign In
        Create Account</value>
        <webElementGuid>20f72bef-7424-48c3-8bb8-a378eade024f</webElementGuid>
    </webElementProperties>
</WebElementEntity>