<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>03f4728c-e6bb-44bd-aaec-ea3991d79e41</elementGuidId>
    <imagePath></imagePath>
    <name>item_dashboard</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/aside[1]/div[1]/ul[1]/li[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Main navigation\"s &gt;&gt; li &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Dashboard</value>
        <webElementGuid>20f72bef-7424-48c3-8bb8-a378eade024f</webElementGuid>
    </webElementProperties>
</WebElementEntity>