<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7a78a268-fa6e-405b-9b76-9626635b4bd5</elementGuidId>
    <imagePath></imagePath>
    <name>div_productImageMask</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[10]/td[2]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(10) &gt; td:nth-child(2) &gt; .ant-image &gt; .ant-image-mask</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>